### ISSUE TITLE
[Bug] The description for field source_type is too long

### ISSUE THREAD

**Issue by calkan-cue** [fivetran/dbt_app_reporting#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The docs part of the source_type columns is too long in bigquery 

### Relevant error log or model output

```shell
12:18:50  38 of 133 START sql table model dbt_t_app_store.stg_apple_store__crashes_platform_version  [RUN]
12:18:51  Unhandled error while executing target/run/apple_store_source/models/stg_apple_store__app_store_territory.sql
400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/dlake/datasets/dbt_t_app_store/tables/stg_apple_store__app_store_territory?prettyPrint=false: The description for field source_type is too long. The maximum length is 1024 characters.
```

### Expected behavior

running without issue or shorter description for that field 

### dbt Project configurations

  app_reporting:
    +schema: app_reporting
  apple_store:
    +schema: apple_store 
  apple_store_source:
    +schema: app_store 
  
  google_play:
    +schema: google_play
  google_play_source:
    +schema: google_play

### Package versions

  - package: fivetran/app_reporting
    version: [">=0.3.0", "<0.4.0"]

### What database are you using dbt with?

bigquery

### dbt Version

Core:
  - installed: 1.4.5
Plugins:
  - bigquery: 1.4.1 

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by calkan-cue** [comment]
Yes we are persisting these docs to the warehouse. Maybe you can see the same if you try as I do.

**Comment by calkan-cue** [comment]
Will there be any action for the ones those persisting the docs in the warehouse or should I just go with override of the documents ? @fivetran-joemarkiewicz

**Comment by fivetran-joemarkiewicz** [comment]
Hi @calkan-cue apologies for the delay, we are bringing this issue into our current sprint and will share more as we investigate and work towards a fix.

**Comment by fivetran-reneeli** [comment]
Hey @calkan-cue! Thanks for opening this up. Our latest release of this package (v0.3.2) addresses this. As such we'll be closing this issue, but let us know if there's anything else!
